CREATE TABLE users (
    id UUID PRIMARY KEY NOT NULL,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    birth_date DATE,
    phone VARCHAR(20) UNIQUE,
    password_hash TEXT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_status CHECK (status IN ('pending', 'active', 'blocked'))
);

CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));

CREATE TABLE roles (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(60) NOT NULL
);

INSERT INTO roles (code, name) VALUES
    ('admin', 'Administrator'),
    ('umkm', 'UMKM'),
    ('customer', 'Customer'),
    ('cs', 'Customer Service'),
    ('finance', 'Finance');

CREATE TABLE user_roles (
    user_id UUID NOT NULL,
    role_id SMALLINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE addresses (
    id UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    label VARCHAR(40),
    recipient_name VARCHAR(120),
    phone VARCHAR(20),
    province_id VARCHAR(20),
    city_id VARCHAR(20),
    district_id VARCHAR(20),
    postal_code VARCHAR(10),
    address_line TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id)
);
