ALTER TABLE vendors
    DROP COLUMN IF EXISTS registered_address,
    ADD COLUMN IF NOT EXISTS province_id VARCHAR(20),
    ADD COLUMN IF NOT EXISTS province_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS city_id VARCHAR(20),
    ADD COLUMN IF NOT EXISTS city_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS district_id VARCHAR(20),
    ADD COLUMN IF NOT EXISTS district_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS subdistrict_id VARCHAR(20),
    ADD COLUMN IF NOT EXISTS subdistrict_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS postal_code VARCHAR(10),
    ADD COLUMN IF NOT EXISTS address_line TEXT;
