CREATE TABLE roles (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(60) NOT NULL
);

INSERT INTO roles (code, name) VALUES
    ('admin', 'Administrator'),
    ('umkm', 'UMKM'),
    ('customer', 'Customer'),
    ('cs', 'Customer Service'),
    ('finance', 'Finance');

CREATE TABLE users (
    id UUID PRIMARY KEY NOT NULL,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    birth_date DATE,
    phone VARCHAR(20) UNIQUE,
    password_hash TEXT NOT NULL,
    role_id SMALLINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    email_verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_status CHECK (status IN ('pending', 'active', 'blocked')),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));

CREATE TABLE email_verification_tokens (
    id UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    invalidated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_email_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_email_verification_tokens_token_hash ON email_verification_tokens (token_hash);
CREATE UNIQUE INDEX uq_email_verification_tokens_user_active ON email_verification_tokens (user_id)
    WHERE consumed_at IS NULL AND invalidated_at IS NULL;
CREATE INDEX idx_email_verification_tokens_expires_at ON email_verification_tokens (expires_at);
CREATE INDEX idx_email_verification_tokens_user_created_at ON email_verification_tokens (user_id, created_at DESC);

CREATE TABLE addresses (
    id UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    label VARCHAR(40),
    recipient_name VARCHAR(120),
    phone VARCHAR(20),
    province_id VARCHAR(20),
    city_id VARCHAR(20),
    district_id VARCHAR(20),
    postal_code VARCHAR(10),
    address_line TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id)
);
