// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: XenPlatformProvider)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_xenplatform_provider.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain XenPlatformProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockXenPlatformProvider is a mock of XenPlatformProvider interface.
type MockXenPlatformProvider struct {
	ctrl     *gomock.Controller
	recorder *MockXenPlatformProviderMockRecorder
	isgomock struct{}
}

// MockXenPlatformProviderMockRecorder is the mock recorder for MockXenPlatformProvider.
type MockXenPlatformProviderMockRecorder struct {
	mock *MockXenPlatformProvider
}

// NewMockXenPlatformProvider creates a new mock instance.
func NewMockXenPlatformProvider(ctrl *gomock.Controller) *MockXenPlatformProvider {
	mock := &MockXenPlatformProvider{ctrl: ctrl}
	mock.recorder = &MockXenPlatformProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXenPlatformProvider) EXPECT() *MockXenPlatformProviderMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockXenPlatformProvider) CreateAccount(ctx context.Context, req domain.XenPlatformCreateAccountRequest) (*domain.XenPlatformAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, req)
	ret0, _ := ret[0].(*domain.XenPlatformAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockXenPlatformProviderMockRecorder) CreateAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockXenPlatformProvider)(nil).CreateAccount), ctx, req)
}

// GetAccount mocks base method.
func (m *MockXenPlatformProvider) GetAccount(ctx context.Context, id string) (*domain.XenPlatformAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, id)
	ret0, _ := ret[0].(*domain.XenPlatformAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockXenPlatformProviderMockRecorder) GetAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockXenPlatformProvider)(nil).GetAccount), ctx, id)
}

// ListAccounts mocks base method.
func (m *MockXenPlatformProvider) ListAccounts(ctx context.Context, params domain.XenPlatformListAccountsParams) (*domain.XenPlatformListAccountsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx, params)
	ret0, _ := ret[0].(*domain.XenPlatformListAccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockXenPlatformProviderMockRecorder) ListAccounts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockXenPlatformProvider)(nil).ListAccounts), ctx, params)
}

// UpdateAccount mocks base method.
func (m *MockXenPlatformProvider) UpdateAccount(ctx context.Context, id string, req domain.XenPlatformUpdateAccountRequest) (*domain.XenPlatformAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, id, req)
	ret0, _ := ret[0].(*domain.XenPlatformAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockXenPlatformProviderMockRecorder) UpdateAccount(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockXenPlatformProvider)(nil).UpdateAccount), ctx, id, req)
}
