// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: AddressRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_address_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain AddressRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAddressRepository is a mock of AddressRepository interface.
type MockAddressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAddressRepositoryMockRecorder
	isgomock struct{}
}

// MockAddressRepositoryMockRecorder is the mock recorder for MockAddressRepository.
type MockAddressRepositoryMockRecorder struct {
	mock *MockAddressRepository
}

// NewMockAddressRepository creates a new mock instance.
func NewMockAddressRepository(ctrl *gomock.Controller) *MockAddressRepository {
	mock := &MockAddressRepository{ctrl: ctrl}
	mock.recorder = &MockAddressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressRepository) EXPECT() *MockAddressRepositoryMockRecorder {
	return m.recorder
}

// ClearDefaultByUser mocks base method.
func (m *MockAddressRepository) ClearDefaultByUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDefaultByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDefaultByUser indicates an expected call of ClearDefaultByUser.
func (mr *MockAddressRepositoryMockRecorder) ClearDefaultByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDefaultByUser", reflect.TypeOf((*MockAddressRepository)(nil).ClearDefaultByUser), ctx, userID)
}

// Create mocks base method.
func (m *MockAddressRepository) Create(ctx context.Context, address *domain.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAddressRepositoryMockRecorder) Create(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAddressRepository)(nil).Create), ctx, address)
}

// Delete mocks base method.
func (m *MockAddressRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAddressRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAddressRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockAddressRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAddressRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAddressRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockAddressRepository) FindByUserID(ctx context.Context, userID uuid.UUID) ([]domain.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockAddressRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockAddressRepository)(nil).FindByUserID), ctx, userID)
}

// FindDefaultByUserID mocks base method.
func (m *MockAddressRepository) FindDefaultByUserID(ctx context.Context, userID uuid.UUID) (*domain.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDefaultByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDefaultByUserID indicates an expected call of FindDefaultByUserID.
func (mr *MockAddressRepositoryMockRecorder) FindDefaultByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDefaultByUserID", reflect.TypeOf((*MockAddressRepository)(nil).FindDefaultByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockAddressRepository) Update(ctx context.Context, address *domain.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAddressRepositoryMockRecorder) Update(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAddressRepository)(nil).Update), ctx, address)
}
