// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: PaymentRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_payment_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain PaymentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockPaymentRepository) CreateEvent(ctx context.Context, event *domain.PaymentEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockPaymentRepositoryMockRecorder) CreateEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockPaymentRepository)(nil).CreateEvent), ctx, event)
}

// CreateInvoice mocks base method.
func (m *MockPaymentRepository) CreateInvoice(ctx context.Context, invoice *domain.PaymentInvoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockPaymentRepositoryMockRecorder) CreateInvoice(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockPaymentRepository)(nil).CreateInvoice), ctx, invoice)
}

// EventExistsByExternalID mocks base method.
func (m *MockPaymentRepository) EventExistsByExternalID(ctx context.Context, externalEventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventExistsByExternalID", ctx, externalEventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventExistsByExternalID indicates an expected call of EventExistsByExternalID.
func (mr *MockPaymentRepositoryMockRecorder) EventExistsByExternalID(ctx, externalEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventExistsByExternalID", reflect.TypeOf((*MockPaymentRepository)(nil).EventExistsByExternalID), ctx, externalEventID)
}

// FindInvoiceByExternalID mocks base method.
func (m *MockPaymentRepository) FindInvoiceByExternalID(ctx context.Context, externalID string) (*domain.PaymentInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInvoiceByExternalID", ctx, externalID)
	ret0, _ := ret[0].(*domain.PaymentInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInvoiceByExternalID indicates an expected call of FindInvoiceByExternalID.
func (mr *MockPaymentRepositoryMockRecorder) FindInvoiceByExternalID(ctx, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInvoiceByExternalID", reflect.TypeOf((*MockPaymentRepository)(nil).FindInvoiceByExternalID), ctx, externalID)
}

// UpdateInvoiceStatus mocks base method.
func (m *MockPaymentRepository) UpdateInvoiceStatus(ctx context.Context, invoiceID uuid.UUID, status string, paidAt *time.Time, paymentMethod, paymentChannel *string, rawPayload map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvoiceStatus", ctx, invoiceID, status, paidAt, paymentMethod, paymentChannel, rawPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInvoiceStatus indicates an expected call of UpdateInvoiceStatus.
func (mr *MockPaymentRepositoryMockRecorder) UpdateInvoiceStatus(ctx, invoiceID, status, paidAt, paymentMethod, paymentChannel, rawPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvoiceStatus", reflect.TypeOf((*MockPaymentRepository)(nil).UpdateInvoiceStatus), ctx, invoiceID, status, paidAt, paymentMethod, paymentChannel, rawPayload)
}
