// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: OTPRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_otp_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain OTPRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOTPRepository is a mock of OTPRepository interface.
type MockOTPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOTPRepositoryMockRecorder
}

// MockOTPRepositoryMockRecorder is the mock recorder for MockOTPRepository.
type MockOTPRepositoryMockRecorder struct {
	mock *MockOTPRepository
}

// NewMockOTPRepository creates a new mock instance.
func NewMockOTPRepository(ctrl *gomock.Controller) *MockOTPRepository {
	mock := &MockOTPRepository{ctrl: ctrl}
	mock.recorder = &MockOTPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTPRepository) EXPECT() *MockOTPRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockOTPRepository) Consume(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockOTPRepositoryMockRecorder) Consume(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockOTPRepository)(nil).Consume), ctx, id)
}

// Create mocks base method.
func (m *MockOTPRepository) Create(ctx context.Context, otp *domain.OTPCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOTPRepositoryMockRecorder) Create(ctx, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOTPRepository)(nil).Create), ctx, otp)
}

// FindActiveByEmailPurpose mocks base method.
func (m *MockOTPRepository) FindActiveByEmailPurpose(ctx context.Context, email, purpose, channel string) (*domain.OTPCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByEmailPurpose", ctx, email, purpose, channel)
	ret0, _ := ret[0].(*domain.OTPCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByEmailPurpose indicates an expected call of FindActiveByEmailPurpose.
func (mr *MockOTPRepositoryMockRecorder) FindActiveByEmailPurpose(ctx, email, purpose, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByEmailPurpose", reflect.TypeOf((*MockOTPRepository)(nil).FindActiveByEmailPurpose), ctx, email, purpose, channel)
}

// FindLatestByEmailPurpose mocks base method.
func (m *MockOTPRepository) FindLatestByEmailPurpose(ctx context.Context, email, purpose, channel string) (*domain.OTPCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestByEmailPurpose", ctx, email, purpose, channel)
	ret0, _ := ret[0].(*domain.OTPCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestByEmailPurpose indicates an expected call of FindLatestByEmailPurpose.
func (mr *MockOTPRepositoryMockRecorder) FindLatestByEmailPurpose(ctx, email, purpose, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestByEmailPurpose", reflect.TypeOf((*MockOTPRepository)(nil).FindLatestByEmailPurpose), ctx, email, purpose, channel)
}

// IncrementAttempts mocks base method.
func (m *MockOTPRepository) IncrementAttempts(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAttempts", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAttempts indicates an expected call of IncrementAttempts.
func (mr *MockOTPRepositoryMockRecorder) IncrementAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAttempts", reflect.TypeOf((*MockOTPRepository)(nil).IncrementAttempts), ctx, id)
}

// InvalidateActiveByEmailPurpose mocks base method.
func (m *MockOTPRepository) InvalidateActiveByEmailPurpose(ctx context.Context, email, purpose, channel string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateActiveByEmailPurpose", ctx, email, purpose, channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateActiveByEmailPurpose indicates an expected call of InvalidateActiveByEmailPurpose.
func (mr *MockOTPRepositoryMockRecorder) InvalidateActiveByEmailPurpose(ctx, email, purpose, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateActiveByEmailPurpose", reflect.TypeOf((*MockOTPRepository)(nil).InvalidateActiveByEmailPurpose), ctx, email, purpose, channel)
}
