// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: VendorRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_vendor_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain VendorRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVendorRepository is a mock of VendorRepository interface.
type MockVendorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVendorRepositoryMockRecorder
	isgomock struct{}
}

// MockVendorRepositoryMockRecorder is the mock recorder for MockVendorRepository.
type MockVendorRepositoryMockRecorder struct {
	mock *MockVendorRepository
}

// NewMockVendorRepository creates a new mock instance.
func NewMockVendorRepository(ctrl *gomock.Controller) *MockVendorRepository {
	mock := &MockVendorRepository{ctrl: ctrl}
	mock.recorder = &MockVendorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendorRepository) EXPECT() *MockVendorRepositoryMockRecorder {
	return m.recorder
}

// ConfirmDocumentsAndUpdateStatus mocks base method.
func (m *MockVendorRepository) ConfirmDocumentsAndUpdateStatus(ctx context.Context, vendorID uuid.UUID, documents []domain.VendorDocument, newStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmDocumentsAndUpdateStatus", ctx, vendorID, documents, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmDocumentsAndUpdateStatus indicates an expected call of ConfirmDocumentsAndUpdateStatus.
func (mr *MockVendorRepositoryMockRecorder) ConfirmDocumentsAndUpdateStatus(ctx, vendorID, documents, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmDocumentsAndUpdateStatus", reflect.TypeOf((*MockVendorRepository)(nil).ConfirmDocumentsAndUpdateStatus), ctx, vendorID, documents, newStatus)
}

// Create mocks base method.
func (m *MockVendorRepository) Create(ctx context.Context, vendor *domain.Vendor, bankAccount *domain.VendorBankAccount, documents []domain.VendorDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, vendor, bankAccount, documents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVendorRepositoryMockRecorder) Create(ctx, vendor, bankAccount, documents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVendorRepository)(nil).Create), ctx, vendor, bankAccount, documents)
}

// FindBankAccountByVendorID mocks base method.
func (m *MockVendorRepository) FindBankAccountByVendorID(ctx context.Context, vendorID uuid.UUID) (*domain.VendorBankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBankAccountByVendorID", ctx, vendorID)
	ret0, _ := ret[0].(*domain.VendorBankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBankAccountByVendorID indicates an expected call of FindBankAccountByVendorID.
func (mr *MockVendorRepositoryMockRecorder) FindBankAccountByVendorID(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBankAccountByVendorID", reflect.TypeOf((*MockVendorRepository)(nil).FindBankAccountByVendorID), ctx, vendorID)
}

// FindByID mocks base method.
func (m *MockVendorRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Vendor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Vendor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockVendorRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockVendorRepository)(nil).FindByID), ctx, id)
}

// FindByOwnerUserID mocks base method.
func (m *MockVendorRepository) FindByOwnerUserID(ctx context.Context, userID uuid.UUID) (*domain.Vendor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Vendor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerUserID indicates an expected call of FindByOwnerUserID.
func (mr *MockVendorRepositoryMockRecorder) FindByOwnerUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerUserID", reflect.TypeOf((*MockVendorRepository)(nil).FindByOwnerUserID), ctx, userID)
}

// FindDocumentsByVendorID mocks base method.
func (m *MockVendorRepository) FindDocumentsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]domain.VendorDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDocumentsByVendorID", ctx, vendorID)
	ret0, _ := ret[0].([]domain.VendorDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDocumentsByVendorID indicates an expected call of FindDocumentsByVendorID.
func (mr *MockVendorRepositoryMockRecorder) FindDocumentsByVendorID(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDocumentsByVendorID", reflect.TypeOf((*MockVendorRepository)(nil).FindDocumentsByVendorID), ctx, vendorID)
}

// List mocks base method.
func (m *MockVendorRepository) List(ctx context.Context, params domain.VendorListParams) ([]domain.Vendor, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]domain.Vendor)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVendorRepositoryMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVendorRepository)(nil).List), ctx, params)
}

// UpdateStatus mocks base method.
func (m *MockVendorRepository) UpdateStatus(ctx context.Context, vendorID uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, vendorID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockVendorRepositoryMockRecorder) UpdateStatus(ctx, vendorID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockVendorRepository)(nil).UpdateStatus), ctx, vendorID, updates)
}
