// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: ShipmentRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_shipment_repo.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain ShipmentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockShipmentRepository is a mock of ShipmentRepository interface.
type MockShipmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShipmentRepositoryMockRecorder
	isgomock struct{}
}

// MockShipmentRepositoryMockRecorder is the mock recorder for MockShipmentRepository.
type MockShipmentRepositoryMockRecorder struct {
	mock *MockShipmentRepository
}

// NewMockShipmentRepository creates a new mock instance.
func NewMockShipmentRepository(ctrl *gomock.Controller) *MockShipmentRepository {
	mock := &MockShipmentRepository{ctrl: ctrl}
	mock.recorder = &MockShipmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShipmentRepository) EXPECT() *MockShipmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShipmentRepository) Create(ctx context.Context, shipment *domain.Shipment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, shipment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShipmentRepositoryMockRecorder) Create(ctx, shipment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShipmentRepository)(nil).Create), ctx, shipment)
}

// FindByOrderID mocks base method.
func (m *MockShipmentRepository) FindByOrderID(ctx context.Context, orderID uuid.UUID) (*domain.Shipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*domain.Shipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockShipmentRepositoryMockRecorder) FindByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockShipmentRepository)(nil).FindByOrderID), ctx, orderID)
}

// UpdateTrackingAndShip mocks base method.
func (m *MockShipmentRepository) UpdateTrackingAndShip(ctx context.Context, orderID uuid.UUID, trackingNo string, shippedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrackingAndShip", ctx, orderID, trackingNo, shippedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrackingAndShip indicates an expected call of UpdateTrackingAndShip.
func (mr *MockShipmentRepositoryMockRecorder) UpdateTrackingAndShip(ctx, orderID, trackingNo, shippedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrackingAndShip", reflect.TypeOf((*MockShipmentRepository)(nil).UpdateTrackingAndShip), ctx, orderID, trackingNo, shippedAt)
}
