// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: VendorVoucherRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_vendor_voucher_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain VendorVoucherRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVendorVoucherRepository is a mock of VendorVoucherRepository interface.
type MockVendorVoucherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVendorVoucherRepositoryMockRecorder
	isgomock struct{}
}

// MockVendorVoucherRepositoryMockRecorder is the mock recorder for MockVendorVoucherRepository.
type MockVendorVoucherRepositoryMockRecorder struct {
	mock *MockVendorVoucherRepository
}

// NewMockVendorVoucherRepository creates a new mock instance.
func NewMockVendorVoucherRepository(ctrl *gomock.Controller) *MockVendorVoucherRepository {
	mock := &MockVendorVoucherRepository{ctrl: ctrl}
	mock.recorder = &MockVendorVoucherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendorVoucherRepository) EXPECT() *MockVendorVoucherRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVendorVoucherRepository) Create(ctx context.Context, voucher *domain.VendorVoucher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, voucher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVendorVoucherRepositoryMockRecorder) Create(ctx, voucher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVendorVoucherRepository)(nil).Create), ctx, voucher)
}

// Delete mocks base method.
func (m *MockVendorVoucherRepository) Delete(ctx context.Context, id, vendorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, vendorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVendorVoucherRepositoryMockRecorder) Delete(ctx, id, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVendorVoucherRepository)(nil).Delete), ctx, id, vendorID)
}

// FindByCode mocks base method.
func (m *MockVendorVoucherRepository) FindByCode(ctx context.Context, vendorID uuid.UUID, code string) (*domain.VendorVoucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, vendorID, code)
	ret0, _ := ret[0].(*domain.VendorVoucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockVendorVoucherRepositoryMockRecorder) FindByCode(ctx, vendorID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockVendorVoucherRepository)(nil).FindByCode), ctx, vendorID, code)
}

// FindByID mocks base method.
func (m *MockVendorVoucherRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.VendorVoucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.VendorVoucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockVendorVoucherRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockVendorVoucherRepository)(nil).FindByID), ctx, id)
}

// GetSummary mocks base method.
func (m *MockVendorVoucherRepository) GetSummary(ctx context.Context, vendorID uuid.UUID) (*domain.VendorVoucherSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, vendorID)
	ret0, _ := ret[0].(*domain.VendorVoucherSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockVendorVoucherRepositoryMockRecorder) GetSummary(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockVendorVoucherRepository)(nil).GetSummary), ctx, vendorID)
}

// ListByVendor mocks base method.
func (m *MockVendorVoucherRepository) ListByVendor(ctx context.Context, vendorID uuid.UUID, params domain.VendorVoucherListParams) ([]domain.VendorVoucher, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVendor", ctx, vendorID, params)
	ret0, _ := ret[0].([]domain.VendorVoucher)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByVendor indicates an expected call of ListByVendor.
func (mr *MockVendorVoucherRepositoryMockRecorder) ListByVendor(ctx, vendorID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVendor", reflect.TypeOf((*MockVendorVoucherRepository)(nil).ListByVendor), ctx, vendorID, params)
}

// Update mocks base method.
func (m *MockVendorVoucherRepository) Update(ctx context.Context, voucher *domain.VendorVoucher, replaceProducts bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, voucher, replaceProducts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVendorVoucherRepositoryMockRecorder) Update(ctx, voucher, replaceProducts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVendorVoucherRepository)(nil).Update), ctx, voucher, replaceProducts)
}
