// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: EmailProvider)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_email_provider.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain EmailProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailProvider is a mock of EmailProvider interface.
type MockEmailProvider struct {
	ctrl     *gomock.Controller
	recorder *MockEmailProviderMockRecorder
	isgomock struct{}
}

// MockEmailProviderMockRecorder is the mock recorder for MockEmailProvider.
type MockEmailProviderMockRecorder struct {
	mock *MockEmailProvider
}

// NewMockEmailProvider creates a new mock instance.
func NewMockEmailProvider(ctrl *gomock.Controller) *MockEmailProvider {
	mock := &MockEmailProvider{ctrl: ctrl}
	mock.recorder = &MockEmailProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailProvider) EXPECT() *MockEmailProviderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockEmailProvider) Send(ctx context.Context, msg domain.EmailMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEmailProviderMockRecorder) Send(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEmailProvider)(nil).Send), ctx, msg)
}
