// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: OrderRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_order_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain OrderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CreateOrderWithItems mocks base method.
func (m *MockOrderRepository) CreateOrderWithItems(ctx context.Context, order *domain.Order, items []domain.OrderItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderWithItems", ctx, order, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderWithItems indicates an expected call of CreateOrderWithItems.
func (mr *MockOrderRepositoryMockRecorder) CreateOrderWithItems(ctx, order, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderWithItems", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrderWithItems), ctx, order, items)
}

// FindByID mocks base method.
func (m *MockOrderRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOrderRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOrderRepository)(nil).FindByID), ctx, id)
}

// FindItemsByOrderID mocks base method.
func (m *MockOrderRepository) FindItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]domain.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]domain.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindItemsByOrderID indicates an expected call of FindItemsByOrderID.
func (mr *MockOrderRepositoryMockRecorder) FindItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindItemsByOrderID", reflect.TypeOf((*MockOrderRepository)(nil).FindItemsByOrderID), ctx, orderID)
}

// RestoreStock mocks base method.
func (m *MockOrderRepository) RestoreStock(ctx context.Context, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreStock", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreStock indicates an expected call of RestoreStock.
func (mr *MockOrderRepositoryMockRecorder) RestoreStock(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreStock", reflect.TypeOf((*MockOrderRepository)(nil).RestoreStock), ctx, orderID)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepository) UpdateOrderStatus(ctx context.Context, orderID uuid.UUID, orderStatus, paymentStatus string, changedBy *uuid.UUID, notes *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderID, orderStatus, paymentStatus, changedBy, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrderStatus(ctx, orderID, orderStatus, paymentStatus, changedBy, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrderStatus), ctx, orderID, orderStatus, paymentStatus, changedBy, notes)
}
