// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: ProductRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_product_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain ProductRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// CountBySlugPrefix mocks base method.
func (m *MockProductRepository) CountBySlugPrefix(ctx context.Context, prefix string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBySlugPrefix", ctx, prefix)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBySlugPrefix indicates an expected call of CountBySlugPrefix.
func (mr *MockProductRepositoryMockRecorder) CountBySlugPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBySlugPrefix", reflect.TypeOf((*MockProductRepository)(nil).CountBySlugPrefix), ctx, prefix)
}

// CountByVendorID mocks base method.
func (m *MockProductRepository) CountByVendorID(ctx context.Context, vendorID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByVendorID", ctx, vendorID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByVendorID indicates an expected call of CountByVendorID.
func (mr *MockProductRepositoryMockRecorder) CountByVendorID(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByVendorID", reflect.TypeOf((*MockProductRepository)(nil).CountByVendorID), ctx, vendorID)
}

// Create mocks base method.
func (m *MockProductRepository) Create(ctx context.Context, product *domain.Product, variants []domain.ProductVariant, images []domain.ProductImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product, variants, images)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductRepositoryMockRecorder) Create(ctx, product, variants, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductRepository)(nil).Create), ctx, product, variants, images)
}

// FindByID mocks base method.
func (m *MockProductRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProductRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProductRepository)(nil).FindByID), ctx, id)
}

// FindBySlug mocks base method.
func (m *MockProductRepository) FindBySlug(ctx context.Context, slug string) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockProductRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockProductRepository)(nil).FindBySlug), ctx, slug)
}

// FindImagesByProductID mocks base method.
func (m *MockProductRepository) FindImagesByProductID(ctx context.Context, productID uuid.UUID) ([]domain.ProductImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindImagesByProductID", ctx, productID)
	ret0, _ := ret[0].([]domain.ProductImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindImagesByProductID indicates an expected call of FindImagesByProductID.
func (mr *MockProductRepositoryMockRecorder) FindImagesByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindImagesByProductID", reflect.TypeOf((*MockProductRepository)(nil).FindImagesByProductID), ctx, productID)
}

// FindVariantByID mocks base method.
func (m *MockProductRepository) FindVariantByID(ctx context.Context, id uuid.UUID) (*domain.ProductVariant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVariantByID", ctx, id)
	ret0, _ := ret[0].(*domain.ProductVariant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVariantByID indicates an expected call of FindVariantByID.
func (mr *MockProductRepositoryMockRecorder) FindVariantByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVariantByID", reflect.TypeOf((*MockProductRepository)(nil).FindVariantByID), ctx, id)
}

// FindVariantsByProductID mocks base method.
func (m *MockProductRepository) FindVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]domain.ProductVariant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVariantsByProductID", ctx, productID)
	ret0, _ := ret[0].([]domain.ProductVariant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVariantsByProductID indicates an expected call of FindVariantsByProductID.
func (mr *MockProductRepositoryMockRecorder) FindVariantsByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVariantsByProductID", reflect.TypeOf((*MockProductRepository)(nil).FindVariantsByProductID), ctx, productID)
}

// GetPublishedDetailForCustomer mocks base method.
func (m *MockProductRepository) GetPublishedDetailForCustomer(ctx context.Context, id uuid.UUID) (*domain.ProductDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedDetailForCustomer", ctx, id)
	ret0, _ := ret[0].(*domain.ProductDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedDetailForCustomer indicates an expected call of GetPublishedDetailForCustomer.
func (mr *MockProductRepositoryMockRecorder) GetPublishedDetailForCustomer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedDetailForCustomer", reflect.TypeOf((*MockProductRepository)(nil).GetPublishedDetailForCustomer), ctx, id)
}

// ListPublishedForCustomer mocks base method.
func (m *MockProductRepository) ListPublishedForCustomer(ctx context.Context, params domain.ProductListParams) ([]domain.ProductListItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublishedForCustomer", ctx, params)
	ret0, _ := ret[0].([]domain.ProductListItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPublishedForCustomer indicates an expected call of ListPublishedForCustomer.
func (mr *MockProductRepositoryMockRecorder) ListPublishedForCustomer(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublishedForCustomer", reflect.TypeOf((*MockProductRepository)(nil).ListPublishedForCustomer), ctx, params)
}

// ListByVendor mocks base method.
func (m *MockProductRepository) ListByVendor(ctx context.Context, vendorID uuid.UUID, params domain.VendorProductListParams) ([]domain.VendorProductListItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVendor", ctx, vendorID, params)
	ret0, _ := ret[0].([]domain.VendorProductListItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByVendor indicates an expected call of ListByVendor.
func (mr *MockProductRepositoryMockRecorder) ListByVendor(ctx, vendorID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVendor", reflect.TypeOf((*MockProductRepository)(nil).ListByVendor), ctx, vendorID, params)
}

// UpdateImages mocks base method.
func (m *MockProductRepository) UpdateImages(ctx context.Context, images []domain.ProductImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImages", ctx, images)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImages indicates an expected call of UpdateImages.
func (mr *MockProductRepositoryMockRecorder) UpdateImages(ctx, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImages", reflect.TypeOf((*MockProductRepository)(nil).UpdateImages), ctx, images)
}
