// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: EmailVerificationTokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_email_verification_token_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain EmailVerificationTokenRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailVerificationTokenRepository is a mock of EmailVerificationTokenRepository interface.
type MockEmailVerificationTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailVerificationTokenRepositoryMockRecorder is the mock recorder for MockEmailVerificationTokenRepository.
type MockEmailVerificationTokenRepositoryMockRecorder struct {
	mock *MockEmailVerificationTokenRepository
}

// NewMockEmailVerificationTokenRepository creates a new mock instance.
func NewMockEmailVerificationTokenRepository(ctrl *gomock.Controller) *MockEmailVerificationTokenRepository {
	mock := &MockEmailVerificationTokenRepository{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationTokenRepository) EXPECT() *MockEmailVerificationTokenRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockEmailVerificationTokenRepository) Consume(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockEmailVerificationTokenRepositoryMockRecorder) Consume(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockEmailVerificationTokenRepository)(nil).Consume), ctx, id)
}

// Create mocks base method.
func (m *MockEmailVerificationTokenRepository) Create(ctx context.Context, token *domain.EmailVerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmailVerificationTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailVerificationTokenRepository)(nil).Create), ctx, token)
}

// FindActiveByTokenHash mocks base method.
func (m *MockEmailVerificationTokenRepository) FindActiveByTokenHash(ctx context.Context, tokenHash string) (*domain.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByTokenHash indicates an expected call of FindActiveByTokenHash.
func (mr *MockEmailVerificationTokenRepositoryMockRecorder) FindActiveByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByTokenHash", reflect.TypeOf((*MockEmailVerificationTokenRepository)(nil).FindActiveByTokenHash), ctx, tokenHash)
}

// FindLatestByUserID mocks base method.
func (m *MockEmailVerificationTokenRepository) FindLatestByUserID(ctx context.Context, userID uuid.UUID) (*domain.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestByUserID indicates an expected call of FindLatestByUserID.
func (mr *MockEmailVerificationTokenRepositoryMockRecorder) FindLatestByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestByUserID", reflect.TypeOf((*MockEmailVerificationTokenRepository)(nil).FindLatestByUserID), ctx, userID)
}

// InvalidateByUserID mocks base method.
func (m *MockEmailVerificationTokenRepository) InvalidateByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByUserID indicates an expected call of InvalidateByUserID.
func (mr *MockEmailVerificationTokenRepositoryMockRecorder) InvalidateByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByUserID", reflect.TypeOf((*MockEmailVerificationTokenRepository)(nil).InvalidateByUserID), ctx, userID)
}
