// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: VendorRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_vendor_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain VendorRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVendorRepository is a mock of VendorRepository interface.
type MockVendorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVendorRepositoryMockRecorder
	isgomock struct{}
}

// MockVendorRepositoryMockRecorder is the mock recorder for MockVendorRepository.
type MockVendorRepositoryMockRecorder struct {
	mock *MockVendorRepository
}

// NewMockVendorRepository creates a new mock instance.
func NewMockVendorRepository(ctrl *gomock.Controller) *MockVendorRepository {
	mock := &MockVendorRepository{ctrl: ctrl}
	mock.recorder = &MockVendorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendorRepository) EXPECT() *MockVendorRepositoryMockRecorder {
	return m.recorder
}

// ApplyWithdrawalWebhookUpdate mocks base method.
func (m *MockVendorRepository) ApplyWithdrawalWebhookUpdate(ctx context.Context, withdrawalID uuid.UUID, newStatus, xenditStatus string, xenditPayoutID, failedReason *string, balanceAction string, completion *domain.WithdrawalCompletionData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyWithdrawalWebhookUpdate", ctx, withdrawalID, newStatus, xenditStatus, xenditPayoutID, failedReason, balanceAction, completion)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyWithdrawalWebhookUpdate indicates an expected call of ApplyWithdrawalWebhookUpdate.
func (mr *MockVendorRepositoryMockRecorder) ApplyWithdrawalWebhookUpdate(ctx, withdrawalID, newStatus, xenditStatus, xenditPayoutID, failedReason, balanceAction, completion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyWithdrawalWebhookUpdate", reflect.TypeOf((*MockVendorRepository)(nil).ApplyWithdrawalWebhookUpdate), ctx, withdrawalID, newStatus, xenditStatus, xenditPayoutID, failedReason, balanceAction, completion)
}

// CompleteWithdrawal mocks base method.
func (m *MockVendorRepository) CompleteWithdrawal(ctx context.Context, vendorID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteWithdrawal", ctx, vendorID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteWithdrawal indicates an expected call of CompleteWithdrawal.
func (mr *MockVendorRepositoryMockRecorder) CompleteWithdrawal(ctx, vendorID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteWithdrawal", reflect.TypeOf((*MockVendorRepository)(nil).CompleteWithdrawal), ctx, vendorID, amount)
}

// ConfirmDocumentsAndUpdateStatus mocks base method.
func (m *MockVendorRepository) ConfirmDocumentsAndUpdateStatus(ctx context.Context, vendorID uuid.UUID, documents []domain.VendorDocument, newStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmDocumentsAndUpdateStatus", ctx, vendorID, documents, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmDocumentsAndUpdateStatus indicates an expected call of ConfirmDocumentsAndUpdateStatus.
func (mr *MockVendorRepositoryMockRecorder) ConfirmDocumentsAndUpdateStatus(ctx, vendorID, documents, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmDocumentsAndUpdateStatus", reflect.TypeOf((*MockVendorRepository)(nil).ConfirmDocumentsAndUpdateStatus), ctx, vendorID, documents, newStatus)
}

// Create mocks base method.
func (m *MockVendorRepository) Create(ctx context.Context, vendor *domain.Vendor, bankAccount *domain.VendorBankAccount, documents []domain.VendorDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, vendor, bankAccount, documents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVendorRepositoryMockRecorder) Create(ctx, vendor, bankAccount, documents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVendorRepository)(nil).Create), ctx, vendor, bankAccount, documents)
}

// CreateMinimal mocks base method.
func (m *MockVendorRepository) CreateMinimal(ctx context.Context, vendor *domain.Vendor, documents []domain.VendorDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMinimal", ctx, vendor, documents)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMinimal indicates an expected call of CreateMinimal.
func (mr *MockVendorRepositoryMockRecorder) CreateMinimal(ctx, vendor, documents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMinimal", reflect.TypeOf((*MockVendorRepository)(nil).CreateMinimal), ctx, vendor, documents)
}

// CreateWithdrawal mocks base method.
func (m *MockVendorRepository) CreateWithdrawal(ctx context.Context, withdrawal *domain.VendorWithdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", ctx, withdrawal)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockVendorRepositoryMockRecorder) CreateWithdrawal(ctx, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockVendorRepository)(nil).CreateWithdrawal), ctx, withdrawal)
}

// CreditBalance mocks base method.
func (m *MockVendorRepository) CreditBalance(ctx context.Context, vendorID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreditBalance", ctx, vendorID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreditBalance indicates an expected call of CreditBalance.
func (mr *MockVendorRepositoryMockRecorder) CreditBalance(ctx, vendorID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreditBalance", reflect.TypeOf((*MockVendorRepository)(nil).CreditBalance), ctx, vendorID, amount)
}

// DebitBalance mocks base method.
func (m *MockVendorRepository) DebitBalance(ctx context.Context, vendorID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebitBalance", ctx, vendorID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// DebitBalance indicates an expected call of DebitBalance.
func (mr *MockVendorRepositoryMockRecorder) DebitBalance(ctx, vendorID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebitBalance", reflect.TypeOf((*MockVendorRepository)(nil).DebitBalance), ctx, vendorID, amount)
}

// FailWithdrawal mocks base method.
func (m *MockVendorRepository) FailWithdrawal(ctx context.Context, vendorID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailWithdrawal", ctx, vendorID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailWithdrawal indicates an expected call of FailWithdrawal.
func (mr *MockVendorRepositoryMockRecorder) FailWithdrawal(ctx, vendorID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailWithdrawal", reflect.TypeOf((*MockVendorRepository)(nil).FailWithdrawal), ctx, vendorID, amount)
}

// FindBankAccountByVendorID mocks base method.
func (m *MockVendorRepository) FindBankAccountByVendorID(ctx context.Context, vendorID uuid.UUID) (*domain.VendorBankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBankAccountByVendorID", ctx, vendorID)
	ret0, _ := ret[0].(*domain.VendorBankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBankAccountByVendorID indicates an expected call of FindBankAccountByVendorID.
func (mr *MockVendorRepositoryMockRecorder) FindBankAccountByVendorID(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBankAccountByVendorID", reflect.TypeOf((*MockVendorRepository)(nil).FindBankAccountByVendorID), ctx, vendorID)
}

// FindByID mocks base method.
func (m *MockVendorRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Vendor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Vendor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockVendorRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockVendorRepository)(nil).FindByID), ctx, id)
}

// FindByOwnerUserID mocks base method.
func (m *MockVendorRepository) FindByOwnerUserID(ctx context.Context, userID uuid.UUID) (*domain.Vendor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Vendor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerUserID indicates an expected call of FindByOwnerUserID.
func (mr *MockVendorRepositoryMockRecorder) FindByOwnerUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerUserID", reflect.TypeOf((*MockVendorRepository)(nil).FindByOwnerUserID), ctx, userID)
}

// FindDocumentsByVendorID mocks base method.
func (m *MockVendorRepository) FindDocumentsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]domain.VendorDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDocumentsByVendorID", ctx, vendorID)
	ret0, _ := ret[0].([]domain.VendorDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDocumentsByVendorID indicates an expected call of FindDocumentsByVendorID.
func (mr *MockVendorRepositoryMockRecorder) FindDocumentsByVendorID(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDocumentsByVendorID", reflect.TypeOf((*MockVendorRepository)(nil).FindDocumentsByVendorID), ctx, vendorID)
}

// FindPayoutBatchByID mocks base method.
func (m *MockVendorRepository) FindPayoutBatchByID(ctx context.Context, id uuid.UUID) (*domain.PayoutBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPayoutBatchByID", ctx, id)
	ret0, _ := ret[0].(*domain.PayoutBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPayoutBatchByID indicates an expected call of FindPayoutBatchByID.
func (mr *MockVendorRepositoryMockRecorder) FindPayoutBatchByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPayoutBatchByID", reflect.TypeOf((*MockVendorRepository)(nil).FindPayoutBatchByID), ctx, id)
}

// FindWithdrawalByID mocks base method.
func (m *MockVendorRepository) FindWithdrawalByID(ctx context.Context, id uuid.UUID) (*domain.VendorWithdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithdrawalByID", ctx, id)
	ret0, _ := ret[0].(*domain.VendorWithdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithdrawalByID indicates an expected call of FindWithdrawalByID.
func (mr *MockVendorRepositoryMockRecorder) FindWithdrawalByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithdrawalByID", reflect.TypeOf((*MockVendorRepository)(nil).FindWithdrawalByID), ctx, id)
}

// GetBalance mocks base method.
func (m *MockVendorRepository) GetBalance(ctx context.Context, vendorID uuid.UUID) (*domain.VendorBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, vendorID)
	ret0, _ := ret[0].(*domain.VendorBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockVendorRepositoryMockRecorder) GetBalance(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockVendorRepository)(nil).GetBalance), ctx, vendorID)
}

// InitBalance mocks base method.
func (m *MockVendorRepository) InitBalance(ctx context.Context, vendorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitBalance", ctx, vendorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitBalance indicates an expected call of InitBalance.
func (mr *MockVendorRepositoryMockRecorder) InitBalance(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitBalance", reflect.TypeOf((*MockVendorRepository)(nil).InitBalance), ctx, vendorID)
}

// List mocks base method.
func (m *MockVendorRepository) List(ctx context.Context, params domain.VendorListParams) ([]domain.Vendor, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]domain.Vendor)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVendorRepositoryMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVendorRepository)(nil).List), ctx, params)
}

// UpdatePayoutBatch mocks base method.
func (m *MockVendorRepository) UpdatePayoutBatch(ctx context.Context, batch *domain.PayoutBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePayoutBatch", ctx, batch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePayoutBatch indicates an expected call of UpdatePayoutBatch.
func (mr *MockVendorRepositoryMockRecorder) UpdatePayoutBatch(ctx, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePayoutBatch", reflect.TypeOf((*MockVendorRepository)(nil).UpdatePayoutBatch), ctx, batch)
}

// UpdateStatus mocks base method.
func (m *MockVendorRepository) UpdateStatus(ctx context.Context, vendorID uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, vendorID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockVendorRepositoryMockRecorder) UpdateStatus(ctx, vendorID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockVendorRepository)(nil).UpdateStatus), ctx, vendorID, updates)
}

// UpdateWithdrawal mocks base method.
func (m *MockVendorRepository) UpdateWithdrawal(ctx context.Context, withdrawal *domain.VendorWithdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithdrawal", ctx, withdrawal)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithdrawal indicates an expected call of UpdateWithdrawal.
func (mr *MockVendorRepositoryMockRecorder) UpdateWithdrawal(ctx, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithdrawal", reflect.TypeOf((*MockVendorRepository)(nil).UpdateWithdrawal), ctx, withdrawal)
}
