// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: CartRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_cart_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain CartRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
	isgomock struct{}
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// ClearItems mocks base method.
func (m *MockCartRepository) ClearItems(ctx context.Context, cartID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearItems", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearItems indicates an expected call of ClearItems.
func (mr *MockCartRepositoryMockRecorder) ClearItems(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearItems", reflect.TypeOf((*MockCartRepository)(nil).ClearItems), ctx, cartID)
}

// Create mocks base method.
func (m *MockCartRepository) Create(ctx context.Context, cart *domain.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCartRepositoryMockRecorder) Create(ctx, cart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCartRepository)(nil).Create), ctx, cart)
}

// DeleteItemsByIDs mocks base method.
func (m *MockCartRepository) DeleteItemsByIDs(ctx context.Context, cartID uuid.UUID, itemIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItemsByIDs", ctx, cartID, itemIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItemsByIDs indicates an expected call of DeleteItemsByIDs.
func (mr *MockCartRepositoryMockRecorder) DeleteItemsByIDs(ctx, cartID, itemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItemsByIDs", reflect.TypeOf((*MockCartRepository)(nil).DeleteItemsByIDs), ctx, cartID, itemIDs)
}

// DeleteItem mocks base method.
func (m *MockCartRepository) DeleteItem(ctx context.Context, itemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockCartRepositoryMockRecorder) DeleteItem(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockCartRepository)(nil).DeleteItem), ctx, itemID)
}

// FindByUserID mocks base method.
func (m *MockCartRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*domain.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockCartRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockCartRepository)(nil).FindByUserID), ctx, userID)
}

// FindItemByCartAndVariant mocks base method.
func (m *MockCartRepository) FindItemByCartAndVariant(ctx context.Context, cartID, variantID uuid.UUID) (*domain.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindItemByCartAndVariant", ctx, cartID, variantID)
	ret0, _ := ret[0].(*domain.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindItemByCartAndVariant indicates an expected call of FindItemByCartAndVariant.
func (mr *MockCartRepositoryMockRecorder) FindItemByCartAndVariant(ctx, cartID, variantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindItemByCartAndVariant", reflect.TypeOf((*MockCartRepository)(nil).FindItemByCartAndVariant), ctx, cartID, variantID)
}

// FindItemByID mocks base method.
func (m *MockCartRepository) FindItemByID(ctx context.Context, itemID uuid.UUID) (*domain.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindItemByID", ctx, itemID)
	ret0, _ := ret[0].(*domain.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindItemByID indicates an expected call of FindItemByID.
func (mr *MockCartRepositoryMockRecorder) FindItemByID(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindItemByID", reflect.TypeOf((*MockCartRepository)(nil).FindItemByID), ctx, itemID)
}

// FindSelectedItemsByCartID mocks base method.
func (m *MockCartRepository) FindSelectedItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]domain.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSelectedItemsByCartID", ctx, cartID)
	ret0, _ := ret[0].([]domain.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSelectedItemsByCartID indicates an expected call of FindSelectedItemsByCartID.
func (mr *MockCartRepositoryMockRecorder) FindSelectedItemsByCartID(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSelectedItemsByCartID", reflect.TypeOf((*MockCartRepository)(nil).FindSelectedItemsByCartID), ctx, cartID)
}

// FindItemsByCartID mocks base method.
func (m *MockCartRepository) FindItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]domain.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindItemsByCartID", ctx, cartID)
	ret0, _ := ret[0].([]domain.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindItemsByCartID indicates an expected call of FindItemsByCartID.
func (mr *MockCartRepositoryMockRecorder) FindItemsByCartID(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindItemsByCartID", reflect.TypeOf((*MockCartRepository)(nil).FindItemsByCartID), ctx, cartID)
}

// UpdateItemQty mocks base method.
func (m *MockCartRepository) UpdateItemQty(ctx context.Context, itemID uuid.UUID, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemQty", ctx, itemID, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemQty indicates an expected call of UpdateItemQty.
func (mr *MockCartRepositoryMockRecorder) UpdateItemQty(ctx, itemID, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemQty", reflect.TypeOf((*MockCartRepository)(nil).UpdateItemQty), ctx, itemID, qty)
}

// UpdateItemSelection mocks base method.
func (m *MockCartRepository) UpdateItemSelection(ctx context.Context, itemID uuid.UUID, isSelected bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemSelection", ctx, itemID, isSelected)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemSelection indicates an expected call of UpdateItemSelection.
func (mr *MockCartRepositoryMockRecorder) UpdateItemSelection(ctx, itemID, isSelected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemSelection", reflect.TypeOf((*MockCartRepository)(nil).UpdateItemSelection), ctx, itemID, isSelected)
}

// UpsertItem mocks base method.
func (m *MockCartRepository) UpsertItem(ctx context.Context, item *domain.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertItem indicates an expected call of UpsertItem.
func (mr *MockCartRepositoryMockRecorder) UpsertItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertItem", reflect.TypeOf((*MockCartRepository)(nil).UpsertItem), ctx, item)
}
