// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: LedgerRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_ledger_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain LedgerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLedgerRepository is a mock of LedgerRepository interface.
type MockLedgerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerRepositoryMockRecorder
	isgomock struct{}
}

// MockLedgerRepositoryMockRecorder is the mock recorder for MockLedgerRepository.
type MockLedgerRepositoryMockRecorder struct {
	mock *MockLedgerRepository
}

// NewMockLedgerRepository creates a new mock instance.
func NewMockLedgerRepository(ctrl *gomock.Controller) *MockLedgerRepository {
	mock := &MockLedgerRepository{ctrl: ctrl}
	mock.recorder = &MockLedgerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerRepository) EXPECT() *MockLedgerRepositoryMockRecorder {
	return m.recorder
}

// CreateJournalWithLines mocks base method.
func (m *MockLedgerRepository) CreateJournalWithLines(ctx context.Context, journal *domain.LedgerJournal, lines []domain.LedgerLine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJournalWithLines", ctx, journal, lines)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJournalWithLines indicates an expected call of CreateJournalWithLines.
func (mr *MockLedgerRepositoryMockRecorder) CreateJournalWithLines(ctx, journal, lines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJournalWithLines", reflect.TypeOf((*MockLedgerRepository)(nil).CreateJournalWithLines), ctx, journal, lines)
}

// FindAccountByCode mocks base method.
func (m *MockLedgerRepository) FindAccountByCode(ctx context.Context, code string) (*domain.LedgerAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccountByCode", ctx, code)
	ret0, _ := ret[0].(*domain.LedgerAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccountByCode indicates an expected call of FindAccountByCode.
func (mr *MockLedgerRepositoryMockRecorder) FindAccountByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccountByCode", reflect.TypeOf((*MockLedgerRepository)(nil).FindAccountByCode), ctx, code)
}
