// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: VendorUseCase)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=internal/usecase/mocks/mock_vendor_usecase.go github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain VendorUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVendorUseCase is a mock of VendorUseCase interface.
type MockVendorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVendorUseCaseMockRecorder
	isgomock struct{}
}

// MockVendorUseCaseMockRecorder is the mock recorder for MockVendorUseCase.
type MockVendorUseCaseMockRecorder struct {
	mock *MockVendorUseCase
}

// NewMockVendorUseCase creates a new mock instance.
func NewMockVendorUseCase(ctrl *gomock.Controller) *MockVendorUseCase {
	mock := &MockVendorUseCase{ctrl: ctrl}
	mock.recorder = &MockVendorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendorUseCase) EXPECT() *MockVendorUseCaseMockRecorder {
	return m.recorder
}

// CreateBankAccount mocks base method.
func (m *MockVendorUseCase) CreateBankAccount(ctx context.Context, vendorID uuid.UUID, req domain.CreateVendorBankAccountRequest) (*domain.CreateVendorBankAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankAccount", ctx, vendorID, req)
	ret0, _ := ret[0].(*domain.CreateVendorBankAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankAccount indicates an expected call of CreateBankAccount.
func (mr *MockVendorUseCaseMockRecorder) CreateBankAccount(ctx, vendorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankAccount", reflect.TypeOf((*MockVendorUseCase)(nil).CreateBankAccount), ctx, vendorID, req)
}

// DeleteBankAccount mocks base method.
func (m *MockVendorUseCase) DeleteBankAccount(ctx context.Context, vendorID, bankAccountID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankAccount", ctx, vendorID, bankAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBankAccount indicates an expected call of DeleteBankAccount.
func (mr *MockVendorUseCaseMockRecorder) DeleteBankAccount(ctx, vendorID, bankAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankAccount", reflect.TypeOf((*MockVendorUseCase)(nil).DeleteBankAccount), ctx, vendorID, bankAccountID)
}

// GetBalance mocks base method.
func (m *MockVendorUseCase) GetBalance(ctx context.Context, vendorID uuid.UUID) (*domain.VendorBalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, vendorID)
	ret0, _ := ret[0].(*domain.VendorBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockVendorUseCaseMockRecorder) GetBalance(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockVendorUseCase)(nil).GetBalance), ctx, vendorID)
}

// GetMe mocks base method.
func (m *MockVendorUseCase) GetMe(ctx context.Context, vendorID uuid.UUID) (*domain.VendorMeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", ctx, vendorID)
	ret0, _ := ret[0].(*domain.VendorMeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockVendorUseCaseMockRecorder) GetMe(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockVendorUseCase)(nil).GetMe), ctx, vendorID)
}

// HandlePayoutWebhook mocks base method.
func (m *MockVendorUseCase) HandlePayoutWebhook(ctx context.Context, payload domain.XenditPayoutWebhookPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePayoutWebhook", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandlePayoutWebhook indicates an expected call of HandlePayoutWebhook.
func (mr *MockVendorUseCaseMockRecorder) HandlePayoutWebhook(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePayoutWebhook", reflect.TypeOf((*MockVendorUseCase)(nil).HandlePayoutWebhook), ctx, payload)
}

// ListBankAccounts mocks base method.
func (m *MockVendorUseCase) ListBankAccounts(ctx context.Context, vendorID uuid.UUID) ([]domain.VendorBankAccountListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBankAccounts", ctx, vendorID)
	ret0, _ := ret[0].([]domain.VendorBankAccountListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBankAccounts indicates an expected call of ListBankAccounts.
func (mr *MockVendorUseCaseMockRecorder) ListBankAccounts(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBankAccounts", reflect.TypeOf((*MockVendorUseCase)(nil).ListBankAccounts), ctx, vendorID)
}

// ListPayoutChannels mocks base method.
func (m *MockVendorUseCase) ListPayoutChannels(ctx context.Context, vendorID uuid.UUID) (*domain.VendorPayoutChannelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayoutChannels", ctx, vendorID)
	ret0, _ := ret[0].(*domain.VendorPayoutChannelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPayoutChannels indicates an expected call of ListPayoutChannels.
func (mr *MockVendorUseCaseMockRecorder) ListPayoutChannels(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayoutChannels", reflect.TypeOf((*MockVendorUseCase)(nil).ListPayoutChannels), ctx, vendorID)
}

// ListWithdrawals mocks base method.
func (m *MockVendorUseCase) ListWithdrawals(ctx context.Context, vendorID uuid.UUID, params domain.VendorWithdrawalListParams) ([]domain.VendorWithdrawalListItem, *domain.PaginationMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithdrawals", ctx, vendorID, params)
	ret0, _ := ret[0].([]domain.VendorWithdrawalListItem)
	ret1, _ := ret[1].(*domain.PaginationMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWithdrawals indicates an expected call of ListWithdrawals.
func (mr *MockVendorUseCaseMockRecorder) ListWithdrawals(ctx, vendorID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithdrawals", reflect.TypeOf((*MockVendorUseCase)(nil).ListWithdrawals), ctx, vendorID, params)
}

// Login mocks base method.
func (m *MockVendorUseCase) Login(ctx context.Context, req domain.VendorLoginRequest) (*domain.VendorLoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*domain.VendorLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockVendorUseCaseMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockVendorUseCase)(nil).Login), ctx, req)
}

// PresignSouvenirStoreProposalDocuments mocks base method.
func (m *MockVendorUseCase) PresignSouvenirStoreProposalDocuments(ctx context.Context, vendorID, userID uuid.UUID, req domain.VendorSouvenirStoreProposalPresignRequest) (*domain.VendorSouvenirStoreProposalPresignResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignSouvenirStoreProposalDocuments", ctx, vendorID, userID, req)
	ret0, _ := ret[0].(*domain.VendorSouvenirStoreProposalPresignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignSouvenirStoreProposalDocuments indicates an expected call of PresignSouvenirStoreProposalDocuments.
func (mr *MockVendorUseCaseMockRecorder) PresignSouvenirStoreProposalDocuments(ctx, vendorID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignSouvenirStoreProposalDocuments", reflect.TypeOf((*MockVendorUseCase)(nil).PresignSouvenirStoreProposalDocuments), ctx, vendorID, userID, req)
}

// RequestRegistrationOTP mocks base method.
func (m *MockVendorUseCase) RequestRegistrationOTP(ctx context.Context, req domain.VendorRegisterOTPRequest) (*domain.VendorRegisterOTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestRegistrationOTP", ctx, req)
	ret0, _ := ret[0].(*domain.VendorRegisterOTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestRegistrationOTP indicates an expected call of RequestRegistrationOTP.
func (mr *MockVendorUseCaseMockRecorder) RequestRegistrationOTP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRegistrationOTP", reflect.TypeOf((*MockVendorUseCase)(nil).RequestRegistrationOTP), ctx, req)
}

// RequestWithdrawal mocks base method.
func (m *MockVendorUseCase) RequestWithdrawal(ctx context.Context, vendorID uuid.UUID, req domain.VendorWithdrawRequest) (*domain.VendorWithdrawResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestWithdrawal", ctx, vendorID, req)
	ret0, _ := ret[0].(*domain.VendorWithdrawResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestWithdrawal indicates an expected call of RequestWithdrawal.
func (mr *MockVendorUseCaseMockRecorder) RequestWithdrawal(ctx, vendorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestWithdrawal", reflect.TypeOf((*MockVendorUseCase)(nil).RequestWithdrawal), ctx, vendorID, req)
}

// SetDefaultBankAccount mocks base method.
func (m *MockVendorUseCase) SetDefaultBankAccount(ctx context.Context, vendorID, bankAccountID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultBankAccount", ctx, vendorID, bankAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultBankAccount indicates an expected call of SetDefaultBankAccount.
func (mr *MockVendorUseCaseMockRecorder) SetDefaultBankAccount(ctx, vendorID, bankAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultBankAccount", reflect.TypeOf((*MockVendorUseCase)(nil).SetDefaultBankAccount), ctx, vendorID, bankAccountID)
}

// SetRegistrationPassword mocks base method.
func (m *MockVendorUseCase) SetRegistrationPassword(ctx context.Context, onboardingID uuid.UUID, req domain.VendorRegistrationPasswordRequest) (*domain.VendorLoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRegistrationPassword", ctx, onboardingID, req)
	ret0, _ := ret[0].(*domain.VendorLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRegistrationPassword indicates an expected call of SetRegistrationPassword.
func (mr *MockVendorUseCaseMockRecorder) SetRegistrationPassword(ctx, onboardingID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegistrationPassword", reflect.TypeOf((*MockVendorUseCase)(nil).SetRegistrationPassword), ctx, onboardingID, req)
}

// SubmitSouvenirStoreProposal mocks base method.
func (m *MockVendorUseCase) SubmitSouvenirStoreProposal(ctx context.Context, vendorID, userID uuid.UUID, req domain.VendorSouvenirStoreProposalRequest) (*domain.VendorSouvenirStoreProposalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitSouvenirStoreProposal", ctx, vendorID, userID, req)
	ret0, _ := ret[0].(*domain.VendorSouvenirStoreProposalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitSouvenirStoreProposal indicates an expected call of SubmitSouvenirStoreProposal.
func (mr *MockVendorUseCaseMockRecorder) SubmitSouvenirStoreProposal(ctx, vendorID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitSouvenirStoreProposal", reflect.TypeOf((*MockVendorUseCase)(nil).SubmitSouvenirStoreProposal), ctx, vendorID, userID, req)
}

// UpdateProfile mocks base method.
func (m *MockVendorUseCase) UpdateProfile(ctx context.Context, vendorID uuid.UUID, req domain.VendorUpdateProfileRequest) (*domain.VendorMeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, vendorID, req)
	ret0, _ := ret[0].(*domain.VendorMeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockVendorUseCaseMockRecorder) UpdateProfile(ctx, vendorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockVendorUseCase)(nil).UpdateProfile), ctx, vendorID, req)
}

// VerifyRegistrationOTP mocks base method.
func (m *MockVendorUseCase) VerifyRegistrationOTP(ctx context.Context, req domain.VendorVerifyRegistrationOTPRequest) (*domain.VendorVerifyRegistrationOTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegistrationOTP", ctx, req)
	ret0, _ := ret[0].(*domain.VendorVerifyRegistrationOTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRegistrationOTP indicates an expected call of VerifyRegistrationOTP.
func (mr *MockVendorUseCaseMockRecorder) VerifyRegistrationOTP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegistrationOTP", reflect.TypeOf((*MockVendorUseCase)(nil).VerifyRegistrationOTP), ctx, req)
}
