// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: RajaOngkirProvider)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_rajaongkir_provider.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain RajaOngkirProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRajaOngkirProvider is a mock of RajaOngkirProvider interface.
type MockRajaOngkirProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRajaOngkirProviderMockRecorder
	isgomock struct{}
}

// MockRajaOngkirProviderMockRecorder is the mock recorder for MockRajaOngkirProvider.
type MockRajaOngkirProviderMockRecorder struct {
	mock *MockRajaOngkirProvider
}

// NewMockRajaOngkirProvider creates a new mock instance.
func NewMockRajaOngkirProvider(ctrl *gomock.Controller) *MockRajaOngkirProvider {
	mock := &MockRajaOngkirProvider{ctrl: ctrl}
	mock.recorder = &MockRajaOngkirProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRajaOngkirProvider) EXPECT() *MockRajaOngkirProviderMockRecorder {
	return m.recorder
}

// CalculateDomesticCost mocks base method.
func (m *MockRajaOngkirProvider) CalculateDomesticCost(ctx context.Context, originDistrictID, destDistrictID string, weightGram int, courierCodes string) ([]domain.ShippingCostOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateDomesticCost", ctx, originDistrictID, destDistrictID, weightGram, courierCodes)
	ret0, _ := ret[0].([]domain.ShippingCostOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateDomesticCost indicates an expected call of CalculateDomesticCost.
func (mr *MockRajaOngkirProviderMockRecorder) CalculateDomesticCost(ctx, originDistrictID, destDistrictID, weightGram, courierCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateDomesticCost", reflect.TypeOf((*MockRajaOngkirProvider)(nil).CalculateDomesticCost), ctx, originDistrictID, destDistrictID, weightGram, courierCodes)
}

// GetCitiesByProvince mocks base method.
func (m *MockRajaOngkirProvider) GetCitiesByProvince(ctx context.Context, provinceID string) ([]domain.ROCity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCitiesByProvince", ctx, provinceID)
	ret0, _ := ret[0].([]domain.ROCity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCitiesByProvince indicates an expected call of GetCitiesByProvince.
func (mr *MockRajaOngkirProviderMockRecorder) GetCitiesByProvince(ctx, provinceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCitiesByProvince", reflect.TypeOf((*MockRajaOngkirProvider)(nil).GetCitiesByProvince), ctx, provinceID)
}

// GetDistrictsByCity mocks base method.
func (m *MockRajaOngkirProvider) GetDistrictsByCity(ctx context.Context, cityID string) ([]domain.RODistrict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistrictsByCity", ctx, cityID)
	ret0, _ := ret[0].([]domain.RODistrict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistrictsByCity indicates an expected call of GetDistrictsByCity.
func (mr *MockRajaOngkirProviderMockRecorder) GetDistrictsByCity(ctx, cityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistrictsByCity", reflect.TypeOf((*MockRajaOngkirProvider)(nil).GetDistrictsByCity), ctx, cityID)
}

// GetProvinces mocks base method.
func (m *MockRajaOngkirProvider) GetProvinces(ctx context.Context) ([]domain.ROProvince, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvinces", ctx)
	ret0, _ := ret[0].([]domain.ROProvince)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvinces indicates an expected call of GetProvinces.
func (mr *MockRajaOngkirProviderMockRecorder) GetProvinces(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvinces", reflect.TypeOf((*MockRajaOngkirProvider)(nil).GetProvinces), ctx)
}

// GetSubdistrictsByDistrict mocks base method.
func (m *MockRajaOngkirProvider) GetSubdistrictsByDistrict(ctx context.Context, districtID string) ([]domain.ROSubdistrict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubdistrictsByDistrict", ctx, districtID)
	ret0, _ := ret[0].([]domain.ROSubdistrict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubdistrictsByDistrict indicates an expected call of GetSubdistrictsByDistrict.
func (mr *MockRajaOngkirProviderMockRecorder) GetSubdistrictsByDistrict(ctx, districtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubdistrictsByDistrict", reflect.TypeOf((*MockRajaOngkirProvider)(nil).GetSubdistrictsByDistrict), ctx, districtID)
}
