// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: VendorOrderRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_vendor_order_repo.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain VendorOrderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVendorOrderRepository is a mock of VendorOrderRepository interface.
type MockVendorOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVendorOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockVendorOrderRepositoryMockRecorder is the mock recorder for MockVendorOrderRepository.
type MockVendorOrderRepositoryMockRecorder struct {
	mock *MockVendorOrderRepository
}

// NewMockVendorOrderRepository creates a new mock instance.
func NewMockVendorOrderRepository(ctrl *gomock.Controller) *MockVendorOrderRepository {
	mock := &MockVendorOrderRepository{ctrl: ctrl}
	mock.recorder = &MockVendorOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendorOrderRepository) EXPECT() *MockVendorOrderRepositoryMockRecorder {
	return m.recorder
}

// FindByIDAndVendor mocks base method.
func (m *MockVendorOrderRepository) FindByIDAndVendor(ctx context.Context, orderID, vendorID uuid.UUID) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDAndVendor", ctx, orderID, vendorID)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDAndVendor indicates an expected call of FindByIDAndVendor.
func (mr *MockVendorOrderRepositoryMockRecorder) FindByIDAndVendor(ctx, orderID, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDAndVendor", reflect.TypeOf((*MockVendorOrderRepository)(nil).FindByIDAndVendor), ctx, orderID, vendorID)
}

// ListByVendor mocks base method.
func (m *MockVendorOrderRepository) ListByVendor(ctx context.Context, vendorID uuid.UUID, params domain.VendorOrderListParams) ([]domain.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVendor", ctx, vendorID, params)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByVendor indicates an expected call of ListByVendor.
func (mr *MockVendorOrderRepositoryMockRecorder) ListByVendor(ctx, vendorID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVendor", reflect.TypeOf((*MockVendorOrderRepository)(nil).ListByVendor), ctx, vendorID, params)
}
