// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: XenditInvoiceProvider)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_xendit_invoice_provider.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain XenditInvoiceProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockXenditInvoiceProvider is a mock of XenditInvoiceProvider interface.
type MockXenditInvoiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockXenditInvoiceProviderMockRecorder
	isgomock struct{}
}

// MockXenditInvoiceProviderMockRecorder is the mock recorder for MockXenditInvoiceProvider.
type MockXenditInvoiceProviderMockRecorder struct {
	mock *MockXenditInvoiceProvider
}

// NewMockXenditInvoiceProvider creates a new mock instance.
func NewMockXenditInvoiceProvider(ctrl *gomock.Controller) *MockXenditInvoiceProvider {
	mock := &MockXenditInvoiceProvider{ctrl: ctrl}
	mock.recorder = &MockXenditInvoiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXenditInvoiceProvider) EXPECT() *MockXenditInvoiceProviderMockRecorder {
	return m.recorder
}

// CreateInvoice mocks base method.
func (m *MockXenditInvoiceProvider) CreateInvoice(ctx context.Context, forUserID string, req domain.XenditInvoiceRequest) (*domain.XenditInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, forUserID, req)
	ret0, _ := ret[0].(*domain.XenditInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockXenditInvoiceProviderMockRecorder) CreateInvoice(ctx, forUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockXenditInvoiceProvider)(nil).CreateInvoice), ctx, forUserID, req)
}
