// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: ShippingServiceRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_shipping_service_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain ShippingServiceRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockShippingServiceRepository is a mock of ShippingServiceRepository interface.
type MockShippingServiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShippingServiceRepositoryMockRecorder
	isgomock struct{}
}

// MockShippingServiceRepositoryMockRecorder is the mock recorder for MockShippingServiceRepository.
type MockShippingServiceRepositoryMockRecorder struct {
	mock *MockShippingServiceRepository
}

// NewMockShippingServiceRepository creates a new mock instance.
func NewMockShippingServiceRepository(ctrl *gomock.Controller) *MockShippingServiceRepository {
	mock := &MockShippingServiceRepository{ctrl: ctrl}
	mock.recorder = &MockShippingServiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShippingServiceRepository) EXPECT() *MockShippingServiceRepositoryMockRecorder {
	return m.recorder
}

// FindByIDs mocks base method.
func (m *MockShippingServiceRepository) FindByIDs(ctx context.Context, ids []uuid.UUID) ([]domain.ShippingService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.ShippingService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockShippingServiceRepositoryMockRecorder) FindByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockShippingServiceRepository)(nil).FindByIDs), ctx, ids)
}

// ListActive mocks base method.
func (m *MockShippingServiceRepository) ListActive(ctx context.Context) ([]domain.ShippingService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]domain.ShippingService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockShippingServiceRepositoryMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockShippingServiceRepository)(nil).ListActive), ctx)
}
