// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: FinanceRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_finance_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain FinanceRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFinanceRepository is a mock of FinanceRepository interface.
type MockFinanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFinanceRepositoryMockRecorder
	isgomock struct{}
}

// MockFinanceRepositoryMockRecorder is the mock recorder for MockFinanceRepository.
type MockFinanceRepositoryMockRecorder struct {
	mock *MockFinanceRepository
}

// NewMockFinanceRepository creates a new mock instance.
func NewMockFinanceRepository(ctrl *gomock.Controller) *MockFinanceRepository {
	mock := &MockFinanceRepository{ctrl: ctrl}
	mock.recorder = &MockFinanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinanceRepository) EXPECT() *MockFinanceRepositoryMockRecorder {
	return m.recorder
}

// GetDashboardSummary mocks base method.
func (m *MockFinanceRepository) GetDashboardSummary(ctx context.Context, period domain.FinancePeriod) (*domain.FinanceDashboardSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardSummary", ctx, period)
	ret0, _ := ret[0].(*domain.FinanceDashboardSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardSummary indicates an expected call of GetDashboardSummary.
func (mr *MockFinanceRepositoryMockRecorder) GetDashboardSummary(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardSummary", reflect.TypeOf((*MockFinanceRepository)(nil).GetDashboardSummary), ctx, period)
}

// ListTodayTransactions mocks base method.
func (m *MockFinanceRepository) ListTodayTransactions(ctx context.Context, dayStart, dayEnd time.Time) ([]domain.FinanceTodayTransactionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodayTransactions", ctx, dayStart, dayEnd)
	ret0, _ := ret[0].([]domain.FinanceTodayTransactionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTodayTransactions indicates an expected call of ListTodayTransactions.
func (mr *MockFinanceRepositoryMockRecorder) ListTodayTransactions(ctx, dayStart, dayEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodayTransactions", reflect.TypeOf((*MockFinanceRepository)(nil).ListTodayTransactions), ctx, dayStart, dayEnd)
}

// GetReportSummary mocks base method.
func (m *MockFinanceRepository) GetReportSummary(ctx context.Context, period domain.FinancePeriod) (*domain.FinanceReportSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportSummary", ctx, period)
	ret0, _ := ret[0].(*domain.FinanceReportSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportSummary indicates an expected call of GetReportSummary.
func (mr *MockFinanceRepositoryMockRecorder) GetReportSummary(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportSummary", reflect.TypeOf((*MockFinanceRepository)(nil).GetReportSummary), ctx, period)
}

// ListReportDailyIncome mocks base method.
func (m *MockFinanceRepository) ListReportDailyIncome(ctx context.Context, period domain.FinancePeriod) ([]domain.FinanceReportDailyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReportDailyIncome", ctx, period)
	ret0, _ := ret[0].([]domain.FinanceReportDailyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReportDailyIncome indicates an expected call of ListReportDailyIncome.
func (mr *MockFinanceRepositoryMockRecorder) ListReportDailyIncome(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReportDailyIncome", reflect.TypeOf((*MockFinanceRepository)(nil).ListReportDailyIncome), ctx, period)
}

// ListTransactions mocks base method.
func (m *MockFinanceRepository) ListTransactions(ctx context.Context, period domain.FinancePeriod, params domain.FinanceListParams) ([]domain.FinanceTransactionItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, period, params)
	ret0, _ := ret[0].([]domain.FinanceTransactionItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockFinanceRepositoryMockRecorder) ListTransactions(ctx, period, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockFinanceRepository)(nil).ListTransactions), ctx, period, params)
}

// GetTransactionSummary mocks base method.
func (m *MockFinanceRepository) GetTransactionSummary(ctx context.Context, period domain.FinancePeriod) (*domain.FinanceTransactionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionSummary", ctx, period)
	ret0, _ := ret[0].(*domain.FinanceTransactionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionSummary indicates an expected call of GetTransactionSummary.
func (mr *MockFinanceRepositoryMockRecorder) GetTransactionSummary(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionSummary", reflect.TypeOf((*MockFinanceRepository)(nil).GetTransactionSummary), ctx, period)
}

// ListPayouts mocks base method.
func (m *MockFinanceRepository) ListPayouts(ctx context.Context, period domain.FinancePeriod, params domain.FinanceListParams) ([]domain.FinancePayoutItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayouts", ctx, period, params)
	ret0, _ := ret[0].([]domain.FinancePayoutItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPayouts indicates an expected call of ListPayouts.
func (mr *MockFinanceRepositoryMockRecorder) ListPayouts(ctx, period, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayouts", reflect.TypeOf((*MockFinanceRepository)(nil).ListPayouts), ctx, period, params)
}

// GetPayoutSummary mocks base method.
func (m *MockFinanceRepository) GetPayoutSummary(ctx context.Context, period domain.FinancePeriod) (*domain.FinancePayoutSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayoutSummary", ctx, period)
	ret0, _ := ret[0].(*domain.FinancePayoutSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayoutSummary indicates an expected call of GetPayoutSummary.
func (mr *MockFinanceRepositoryMockRecorder) GetPayoutSummary(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayoutSummary", reflect.TypeOf((*MockFinanceRepository)(nil).GetPayoutSummary), ctx, period)
}

// ListRefunds mocks base method.
func (m *MockFinanceRepository) ListRefunds(ctx context.Context, period domain.FinancePeriod, params domain.FinanceListParams) ([]domain.FinanceRefundItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRefunds", ctx, period, params)
	ret0, _ := ret[0].([]domain.FinanceRefundItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRefunds indicates an expected call of ListRefunds.
func (mr *MockFinanceRepositoryMockRecorder) ListRefunds(ctx, period, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRefunds", reflect.TypeOf((*MockFinanceRepository)(nil).ListRefunds), ctx, period, params)
}

// GetRefundSummary mocks base method.
func (m *MockFinanceRepository) GetRefundSummary(ctx context.Context, period domain.FinancePeriod) (*domain.FinanceRefundSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefundSummary", ctx, period)
	ret0, _ := ret[0].(*domain.FinanceRefundSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefundSummary indicates an expected call of GetRefundSummary.
func (mr *MockFinanceRepositoryMockRecorder) GetRefundSummary(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefundSummary", reflect.TypeOf((*MockFinanceRepository)(nil).GetRefundSummary), ctx, period)
}

// GetRefundRecord mocks base method.
func (m *MockFinanceRepository) GetRefundRecord(ctx context.Context, refundID uuid.UUID) (*domain.RefundRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefundRecord", ctx, refundID)
	ret0, _ := ret[0].(*domain.RefundRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefundRecord indicates an expected call of GetRefundRecord.
func (mr *MockFinanceRepositoryMockRecorder) GetRefundRecord(ctx, refundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefundRecord", reflect.TypeOf((*MockFinanceRepository)(nil).GetRefundRecord), ctx, refundID)
}

// GetRefundDisbursementContext mocks base method.
func (m *MockFinanceRepository) GetRefundDisbursementContext(ctx context.Context, refundID uuid.UUID) (*domain.RefundDisbursementContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefundDisbursementContext", ctx, refundID)
	ret0, _ := ret[0].(*domain.RefundDisbursementContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefundDisbursementContext indicates an expected call of GetRefundDisbursementContext.
func (mr *MockFinanceRepositoryMockRecorder) GetRefundDisbursementContext(ctx, refundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefundDisbursementContext", reflect.TypeOf((*MockFinanceRepository)(nil).GetRefundDisbursementContext), ctx, refundID)
}

// GetRefundVendorBalanceSnapshot mocks base method.
func (m *MockFinanceRepository) GetRefundVendorBalanceSnapshot(ctx context.Context, orderID uuid.UUID) (*domain.RefundVendorBalanceSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefundVendorBalanceSnapshot", ctx, orderID)
	ret0, _ := ret[0].(*domain.RefundVendorBalanceSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefundVendorBalanceSnapshot indicates an expected call of GetRefundVendorBalanceSnapshot.
func (mr *MockFinanceRepositoryMockRecorder) GetRefundVendorBalanceSnapshot(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefundVendorBalanceSnapshot", reflect.TypeOf((*MockFinanceRepository)(nil).GetRefundVendorBalanceSnapshot), ctx, orderID)
}

// GetPayoutRecord mocks base method.
func (m *MockFinanceRepository) GetPayoutRecord(ctx context.Context, payoutID uuid.UUID) (*domain.PayoutRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayoutRecord", ctx, payoutID)
	ret0, _ := ret[0].(*domain.PayoutRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayoutRecord indicates an expected call of GetPayoutRecord.
func (mr *MockFinanceRepositoryMockRecorder) GetPayoutRecord(ctx, payoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayoutRecord", reflect.TypeOf((*MockFinanceRepository)(nil).GetPayoutRecord), ctx, payoutID)
}

// IsOrderSettlementCompleted mocks base method.
func (m *MockFinanceRepository) IsOrderSettlementCompleted(ctx context.Context, orderID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOrderSettlementCompleted", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOrderSettlementCompleted indicates an expected call of IsOrderSettlementCompleted.
func (mr *MockFinanceRepositoryMockRecorder) IsOrderSettlementCompleted(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOrderSettlementCompleted", reflect.TypeOf((*MockFinanceRepository)(nil).IsOrderSettlementCompleted), ctx, orderID)
}

// SetRefundPayoutInitiated mocks base method.
func (m *MockFinanceRepository) SetRefundPayoutInitiated(ctx context.Context, refundID uuid.UUID, actorID uuid.UUID, strategy string, referenceID string, channelCode string, bankName string, accountHolderName string, accountLast4 string, payoutID *string, payoutStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefundPayoutInitiated", ctx, refundID, actorID, strategy, referenceID, channelCode, bankName, accountHolderName, accountLast4, payoutID, payoutStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRefundPayoutInitiated indicates an expected call of SetRefundPayoutInitiated.
func (mr *MockFinanceRepositoryMockRecorder) SetRefundPayoutInitiated(ctx, refundID, actorID, strategy, referenceID, channelCode, bankName, accountHolderName, accountLast4, payoutID, payoutStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefundPayoutInitiated", reflect.TypeOf((*MockFinanceRepository)(nil).SetRefundPayoutInitiated), ctx, refundID, actorID, strategy, referenceID, channelCode, bankName, accountHolderName, accountLast4, payoutID, payoutStatus)
}

// SetRefundPayoutFailed mocks base method.
func (m *MockFinanceRepository) SetRefundPayoutFailed(ctx context.Context, refundID uuid.UUID, payoutStatus string, failedReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefundPayoutFailed", ctx, refundID, payoutStatus, failedReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRefundPayoutFailed indicates an expected call of SetRefundPayoutFailed.
func (mr *MockFinanceRepositoryMockRecorder) SetRefundPayoutFailed(ctx, refundID, payoutStatus, failedReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefundPayoutFailed", reflect.TypeOf((*MockFinanceRepository)(nil).SetRefundPayoutFailed), ctx, refundID, payoutStatus, failedReason)
}

// ApplyRefundPayoutWebhookUpdate mocks base method.
func (m *MockFinanceRepository) ApplyRefundPayoutWebhookUpdate(ctx context.Context, referenceID string, payoutID string, payoutStatus string, failedReason *string, completedAt *time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyRefundPayoutWebhookUpdate", ctx, referenceID, payoutID, payoutStatus, failedReason, completedAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyRefundPayoutWebhookUpdate indicates an expected call of ApplyRefundPayoutWebhookUpdate.
func (mr *MockFinanceRepositoryMockRecorder) ApplyRefundPayoutWebhookUpdate(ctx, referenceID, payoutID, payoutStatus, failedReason, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRefundPayoutWebhookUpdate", reflect.TypeOf((*MockFinanceRepository)(nil).ApplyRefundPayoutWebhookUpdate), ctx, referenceID, payoutID, payoutStatus, failedReason, completedAt)
}

// UpdateRefundStatus mocks base method.
func (m *MockFinanceRepository) UpdateRefundStatus(ctx context.Context, refundID uuid.UUID, status string, actorID uuid.UUID) (*domain.StatusActionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefundStatus", ctx, refundID, status, actorID)
	ret0, _ := ret[0].(*domain.StatusActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRefundStatus indicates an expected call of UpdateRefundStatus.
func (mr *MockFinanceRepositoryMockRecorder) UpdateRefundStatus(ctx, refundID, status, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefundStatus", reflect.TypeOf((*MockFinanceRepository)(nil).UpdateRefundStatus), ctx, refundID, status, actorID)
}

// UpdatePayoutStatus mocks base method.
func (m *MockFinanceRepository) UpdatePayoutStatus(ctx context.Context, payoutID uuid.UUID, status string, actorID uuid.UUID) (*domain.StatusActionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePayoutStatus", ctx, payoutID, status, actorID)
	ret0, _ := ret[0].(*domain.StatusActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePayoutStatus indicates an expected call of UpdatePayoutStatus.
func (mr *MockFinanceRepositoryMockRecorder) UpdatePayoutStatus(ctx, payoutID, status, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePayoutStatus", reflect.TypeOf((*MockFinanceRepository)(nil).UpdatePayoutStatus), ctx, payoutID, status, actorID)
}

// SetRefundGatewayInitiated mocks base method.
func (m *MockFinanceRepository) SetRefundGatewayInitiated(ctx context.Context, refundID uuid.UUID, xenditRefundID string, refundMethod string, payoutReferenceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefundGatewayInitiated", ctx, refundID, xenditRefundID, refundMethod, payoutReferenceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRefundGatewayInitiated indicates an expected call of SetRefundGatewayInitiated.
func (mr *MockFinanceRepositoryMockRecorder) SetRefundGatewayInitiated(ctx, refundID, xenditRefundID, refundMethod, payoutReferenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefundGatewayInitiated", reflect.TypeOf((*MockFinanceRepository)(nil).SetRefundGatewayInitiated), ctx, refundID, xenditRefundID, refundMethod, payoutReferenceID)
}

// ApplyRefundGatewayWebhookUpdate mocks base method.
func (m *MockFinanceRepository) ApplyRefundGatewayWebhookUpdate(ctx context.Context, referenceID string, xenditRefundID string, status string, failureCode *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyRefundGatewayWebhookUpdate", ctx, referenceID, xenditRefundID, status, failureCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyRefundGatewayWebhookUpdate indicates an expected call of ApplyRefundGatewayWebhookUpdate.
func (mr *MockFinanceRepositoryMockRecorder) ApplyRefundGatewayWebhookUpdate(ctx, referenceID, xenditRefundID, status, failureCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRefundGatewayWebhookUpdate", reflect.TypeOf((*MockFinanceRepository)(nil).ApplyRefundGatewayWebhookUpdate), ctx, referenceID, xenditRefundID, status, failureCode)
}

// UpdateOrderPaymentStatus mocks base method.
func (m *MockFinanceRepository) UpdateOrderPaymentStatus(ctx context.Context, orderID uuid.UUID, paymentStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderPaymentStatus", ctx, orderID, paymentStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderPaymentStatus indicates an expected call of UpdateOrderPaymentStatus.
func (mr *MockFinanceRepositoryMockRecorder) UpdateOrderPaymentStatus(ctx, orderID, paymentStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderPaymentStatus", reflect.TypeOf((*MockFinanceRepository)(nil).UpdateOrderPaymentStatus), ctx, orderID, paymentStatus)
}
