// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: WishlistRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_wishlist_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain WishlistRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWishlistRepository is a mock of WishlistRepository interface.
type MockWishlistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWishlistRepositoryMockRecorder
	isgomock struct{}
}

// MockWishlistRepositoryMockRecorder is the mock recorder for MockWishlistRepository.
type MockWishlistRepositoryMockRecorder struct {
	mock *MockWishlistRepository
}

// NewMockWishlistRepository creates a new mock instance.
func NewMockWishlistRepository(ctrl *gomock.Controller) *MockWishlistRepository {
	mock := &MockWishlistRepository{ctrl: ctrl}
	mock.recorder = &MockWishlistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWishlistRepository) EXPECT() *MockWishlistRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockWishlistRepository) Add(ctx context.Context, item *domain.WishlistItem) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, item)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockWishlistRepositoryMockRecorder) Add(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockWishlistRepository)(nil).Add), ctx, item)
}

// DeleteByUserAndProduct mocks base method.
func (m *MockWishlistRepository) DeleteByUserAndProduct(ctx context.Context, userID, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserAndProduct", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserAndProduct indicates an expected call of DeleteByUserAndProduct.
func (mr *MockWishlistRepositoryMockRecorder) DeleteByUserAndProduct(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserAndProduct", reflect.TypeOf((*MockWishlistRepository)(nil).DeleteByUserAndProduct), ctx, userID, productID)
}

// Exists mocks base method.
func (m *MockWishlistRepository) Exists(ctx context.Context, userID, productID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, userID, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockWishlistRepositoryMockRecorder) Exists(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockWishlistRepository)(nil).Exists), ctx, userID, productID)
}

// ListByUser mocks base method.
func (m *MockWishlistRepository) ListByUser(ctx context.Context, userID uuid.UUID, params domain.WishlistListParams) ([]domain.WishlistItemResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, params)
	ret0, _ := ret[0].([]domain.WishlistItemResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockWishlistRepositoryMockRecorder) ListByUser(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockWishlistRepository)(nil).ListByUser), ctx, userID, params)
}
