// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: VendorCourierRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_vendor_courier_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain VendorCourierRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVendorCourierRepository is a mock of VendorCourierRepository interface.
type MockVendorCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVendorCourierRepositoryMockRecorder
	isgomock struct{}
}

// MockVendorCourierRepositoryMockRecorder is the mock recorder for MockVendorCourierRepository.
type MockVendorCourierRepositoryMockRecorder struct {
	mock *MockVendorCourierRepository
}

// NewMockVendorCourierRepository creates a new mock instance.
func NewMockVendorCourierRepository(ctrl *gomock.Controller) *MockVendorCourierRepository {
	mock := &MockVendorCourierRepository{ctrl: ctrl}
	mock.recorder = &MockVendorCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendorCourierRepository) EXPECT() *MockVendorCourierRepositoryMockRecorder {
	return m.recorder
}

// DeleteByVendorAndCourier mocks base method.
func (m *MockVendorCourierRepository) DeleteByVendorAndCourier(ctx context.Context, vendorID uuid.UUID, courierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByVendorAndCourier", ctx, vendorID, courierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByVendorAndCourier indicates an expected call of DeleteByVendorAndCourier.
func (mr *MockVendorCourierRepositoryMockRecorder) DeleteByVendorAndCourier(ctx, vendorID, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByVendorAndCourier", reflect.TypeOf((*MockVendorCourierRepository)(nil).DeleteByVendorAndCourier), ctx, vendorID, courierID)
}

// FindByVendorID mocks base method.
func (m *MockVendorCourierRepository) FindByVendorID(ctx context.Context, vendorID uuid.UUID) ([]domain.VendorCourierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByVendorID", ctx, vendorID)
	ret0, _ := ret[0].([]domain.VendorCourierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByVendorID indicates an expected call of FindByVendorID.
func (mr *MockVendorCourierRepositoryMockRecorder) FindByVendorID(ctx, vendorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByVendorID", reflect.TypeOf((*MockVendorCourierRepository)(nil).FindByVendorID), ctx, vendorID)
}

// SetCouriers mocks base method.
func (m *MockVendorCourierRepository) SetCouriers(ctx context.Context, vendorID uuid.UUID, courierIDs []int) ([]domain.VendorCourierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCouriers", ctx, vendorID, courierIDs)
	ret0, _ := ret[0].([]domain.VendorCourierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCouriers indicates an expected call of SetCouriers.
func (mr *MockVendorCourierRepositoryMockRecorder) SetCouriers(ctx, vendorID, courierIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCouriers", reflect.TypeOf((*MockVendorCourierRepository)(nil).SetCouriers), ctx, vendorID, courierIDs)
}
