// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: XenditPayoutProvider)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_xendit_payout_provider.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain XenditPayoutProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockXenditPayoutProvider is a mock of XenditPayoutProvider interface.
type MockXenditPayoutProvider struct {
	ctrl     *gomock.Controller
	recorder *MockXenditPayoutProviderMockRecorder
	isgomock struct{}
}

// MockXenditPayoutProviderMockRecorder is the mock recorder for MockXenditPayoutProvider.
type MockXenditPayoutProviderMockRecorder struct {
	mock *MockXenditPayoutProvider
}

// NewMockXenditPayoutProvider creates a new mock instance.
func NewMockXenditPayoutProvider(ctrl *gomock.Controller) *MockXenditPayoutProvider {
	mock := &MockXenditPayoutProvider{ctrl: ctrl}
	mock.recorder = &MockXenditPayoutProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXenditPayoutProvider) EXPECT() *MockXenditPayoutProviderMockRecorder {
	return m.recorder
}

// CreatePayout mocks base method.
func (m *MockXenditPayoutProvider) CreatePayout(ctx context.Context, forUserID, idempotencyKey string, req domain.XenditPayoutRequest) (*domain.XenditPayoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayout", ctx, forUserID, idempotencyKey, req)
	ret0, _ := ret[0].(*domain.XenditPayoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayout indicates an expected call of CreatePayout.
func (mr *MockXenditPayoutProviderMockRecorder) CreatePayout(ctx, forUserID, idempotencyKey, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayout", reflect.TypeOf((*MockXenditPayoutProvider)(nil).CreatePayout), ctx, forUserID, idempotencyKey, req)
}

// GetTransactionByReference mocks base method.
func (m *MockXenditPayoutProvider) GetTransactionByReference(ctx context.Context, forUserID, referenceID string) (*domain.XenditTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByReference", ctx, forUserID, referenceID)
	ret0, _ := ret[0].(*domain.XenditTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByReference indicates an expected call of GetTransactionByReference.
func (mr *MockXenditPayoutProviderMockRecorder) GetTransactionByReference(ctx, forUserID, referenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByReference", reflect.TypeOf((*MockXenditPayoutProvider)(nil).GetTransactionByReference), ctx, forUserID, referenceID)
}
