// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain (interfaces: ReviewRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mocks/mock_review_repository.go -package=mocks github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain ReviewRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/media-inovasi-strategis/haji-umroh-store-be/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
	isgomock struct{}
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// CreateWithImages mocks base method.
func (m *MockReviewRepository) CreateWithImages(ctx context.Context, review *domain.ProductReview, images []domain.ProductReviewImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithImages", ctx, review, images)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithImages indicates an expected call of CreateWithImages.
func (mr *MockReviewRepositoryMockRecorder) CreateWithImages(ctx, review, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithImages", reflect.TypeOf((*MockReviewRepository)(nil).CreateWithImages), ctx, review, images)
}

// ExistsByUserAndOrderItem mocks base method.
func (m *MockReviewRepository) ExistsByUserAndOrderItem(ctx context.Context, userID, orderItemID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUserAndOrderItem", ctx, userID, orderItemID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByUserAndOrderItem indicates an expected call of ExistsByUserAndOrderItem.
func (mr *MockReviewRepositoryMockRecorder) ExistsByUserAndOrderItem(ctx, userID, orderItemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUserAndOrderItem", reflect.TypeOf((*MockReviewRepository)(nil).ExistsByUserAndOrderItem), ctx, userID, orderItemID)
}

// GetStatsByProductID mocks base method.
func (m *MockReviewRepository) GetStatsByProductID(ctx context.Context, productID uuid.UUID) (*domain.ProductReviewStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsByProductID", ctx, productID)
	ret0, _ := ret[0].(*domain.ProductReviewStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsByProductID indicates an expected call of GetStatsByProductID.
func (mr *MockReviewRepositoryMockRecorder) GetStatsByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsByProductID", reflect.TypeOf((*MockReviewRepository)(nil).GetStatsByProductID), ctx, productID)
}

// ListByProductID mocks base method.
func (m *MockReviewRepository) ListByProductID(ctx context.Context, productID uuid.UUID, params domain.ProductReviewListParams) ([]domain.ProductReviewListItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProductID", ctx, productID, params)
	ret0, _ := ret[0].([]domain.ProductReviewListItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByProductID indicates an expected call of ListByProductID.
func (mr *MockReviewRepositoryMockRecorder) ListByProductID(ctx, productID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProductID", reflect.TypeOf((*MockReviewRepository)(nil).ListByProductID), ctx, productID, params)
}

// ListByVendor mocks base method.
func (m *MockReviewRepository) ListByVendor(ctx context.Context, vendorID uuid.UUID, page, limit int) ([]domain.VendorReviewItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVendor", ctx, vendorID, page, limit)
	ret0, _ := ret[0].([]domain.VendorReviewItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByVendor indicates an expected call of ListByVendor.
func (mr *MockReviewRepositoryMockRecorder) ListByVendor(ctx, vendorID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVendor", reflect.TypeOf((*MockReviewRepository)(nil).ListByVendor), ctx, vendorID, page, limit)
}
